### ISSUE TITLE
6.3.4 not working with QGIS 3.16.5

### ISSUE THREAD

**Issue by zigertiger** [opengisch/QgisModelBaker#487]
We use QGIS 3.16.5 and have ModelBaker 6.3.4 installed. When trying to generate a project from a pre-configured PostGIS schema, the following error message is thrown:

```
AttributeError: 'NoneType' object has no attribute 'split' 
Traceback (most recent call last):
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\generate_project.py", line 358, in accepted
    available_layers = generator.layers()
  File "C:/Users/peter.staub/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\generator\generator.py", line 116, in layers
    short_name = record['ili_name'].split('.')[-1] if 'ili_name' in record else ''
AttributeError: 'NoneType' object has no attribute 'split'


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.16.5-Hannover Hannover, 58ba7c1ed6 
```

No idea how to overcome this...
Thanks in advance for any help.

-- Peter

**Comment by m-kuhn** [comment]
Just from a first look at the trace, this doesn't look like it's related to the qgis version.
Which model are you using?

**Comment by zigertiger** [comment]
Now, that's a bit strange. I just re-configured the database schema anew and now it works. Maybe the preceding schema was configured using an ili2pg version too old for now...

Anyway, thank you.

Model: GL_OrtsbildDenkmalschutzArchaeologie_V2
