### ISSUE TITLE
There is a Problem with Version 7.9.1

### ISSUE THREAD

**Issue by KTAI-GIS** [opengisch/QgisModelBaker#945]
Hi Dave
Model Baker is not working anymore with Version 7.9.1
I got the error message 
Generate QGIS from existing Database leads to a python error.

2024-07-12T21:01:09     WARNING    Traceback (most recent call last):
              File "C:\Users/lfdmp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\workflow_wizard.py", line 423, in id_changed
              self.generate_database_selection_page.restore_configuration(
              File "C:\Users/lfdmp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 121, in restore_configuration
              self._lst_panel[mode].set_fields(configuration)
             AttributeError: 'NoneType' object has no attribute 'set_fields'

**Comment by MiKa-RegEntw** [comment]
Hey guys, i have also problems with the new version. but a diffrent error.

2024-07-15T11:07:12     WARNING    Traceback (most recent call last):
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 182, in nextId
              return self.workflow_wizard.next_id()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\workflow_wizard.py", line 239, in next_id
              if self.import_database_selection_page.is_valid():
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 154, in is_valid
              res, message = self._lst_panel[db_id].is_valid()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'is_valid'

**Comment by signedav** [comment]
Thanks I'll have a look

**Comment by signedav** [comment]
Opened again, since I'm not 100 sure if it's solved because I could never reproduce it on my own system.

Anyway I'm confident it's solved with the Release 7.9.2 I just published.

Can you please checke again @KTAI-GIS @MiKa-RegEntw

**Comment by MiKa-RegEntw** [comment]
<img width="534" alt="image" src="https://github.com/user-attachments/assets/713648fc-af37-467a-836f-b474422492b6">
<img width="536" alt="image" src="https://github.com/user-attachments/assets/74f28228-8474-4057-b236-3d13282cd6e5">

2024-07-16T14:04:49     WARNING    Traceback (most recent call last):
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\workflow_wizard.py", line 418, in id_changed
              self.import_database_selection_page.restore_configuration(
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 117, in restore_configuration
              self._lst_panel[db_id].set_fields(configuration)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'set_fields'

Unfortunatly my error sill exist. I download the Version 7.4.2 and there it worked. 

But thanks for trying

**Comment by MiKa-RegEntw** [comment]
I also tried diffrent Sources, but the error keeps coming. It is not the same but it is there: 2024-07-16T14:07:05     WARNING    Traceback (most recent call last):
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 183, in nextId
              return self.workflow_wizard.next_id()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\workflow_wizard.py", line 239, in next_id
              if self.import_database_selection_page.is_valid():
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Michael/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\database_selection_page.py", line 155, in is_valid
              res, message = self._lst_panel[db_id].is_valid()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'is_valid'

**Comment by webrian** [comment]
We have the same issue with
* QGIS 3.28.6
* Model Baker 7.9.1 and 7.9.2
* Python Version 3.9

It works with
* QGIS 3.38 and
* Python 3.10

**Comment by signedav** [comment]
> Unfortunatly my error sill exist. I download the Version 7.4.2 and there it worked.

Could you try with 7.8.4?

**Comment by signedav** [comment]
> It works with * Python 3.10

Ah. Interresting. I'll follow this lead.

**Comment by webrian** [comment]
> We have the same issue with

Windows

> 
>     * QGIS 3.28.6
> 
>     * Model Baker 7.9.1 and 7.9.2
> 
>     * Python Version 3.9
> 
> 
> It works with

Ubuntu

> 
>     * QGIS 3.38 and
> 
>     * Python 3.10

It fails on
* Windows
* QGIS 3.34
* Model Baker 7.9.2
* Python 3.12

**Comment by MiKa-RegEntw** [comment]
> > Unfortunatly my error sill exist. I download the Version 7.4.2 and there it worked.
> 
> Could you try with 7.8.4?

Not working, i tried that first.

**Comment by signedav** [comment]
Would be awesome to know with what minor version (second number) it stopped running.

**Comment by KTAI-GIS** [comment]
Hi there
I’ve deinstalled the 7.9.2 then closed QGIS. manually deleted the QGISModelBaker Directory. Restarted QGIS and installed Version 7.8.4.
Restarted QGIS and Version 7.8.4 was working.
Kind regards
Pascal


Von: MiKa-RegEntw ***@***.***>
Gesendet: Dienstag, 16. Juli 2024 15:01
An: opengisch/QgisModelBaker ***@***.***>
Cc: Megert Pascal AI ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QgisModelBaker] There is a Problem with Version 7.9.1 (Issue #945)


Could you try with 7.8.4?

Not working, i tried that first.

Is 7.4.2 the last working version?

I tried until version 4.7.0, then I got frustrated and jumped to the version where I was sure it would work, because I used it back then

**Comment by KTAI-GIS** [comment]
My Configuration with QGIS

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2<https://github.com/qgis/QGIS/commit/50adba36f2>
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009
Active Python plugins
document_management_system
0.3.3
geocat_export
v1.0.1
linking_relation_editor
v1.3.0
numericalDigitize
0.4.7
QgisModelBaker
v7.8.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99


Von: MiKa-RegEntw ***@***.***>
Gesendet: Dienstag, 16. Juli 2024 15:01
An: opengisch/QgisModelBaker ***@***.***>
Cc: Megert Pascal AI ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QgisModelBaker] There is a Problem with Version 7.9.1 (Issue #945)


Could you try with 7.8.4?

Not working, i tried that first.

Is 7.4.2 the last working version?

I tried until version 4.7.0, then I got frustrated and jumped to the version where I was sure it would work, because I used it back then

**Comment by KTAI-GIS** [comment]
Hi Dave
I’m quit sure that 7.9.0 was working and the problem began with the version 7.9.1
Kind regards
Pascal

Von: signedav ***@***.***>
Gesendet: Dienstag, 16. Juli 2024 15:06
An: opengisch/QgisModelBaker ***@***.***>
Cc: Megert Pascal AI ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QgisModelBaker] There is a Problem with Version 7.9.1 (Issue #945)


Would be awesome to know with what minor version (second number) it stopped running.

**Comment by signedav** [comment]
Note to myself:

Works on @lindacamathias 's system
![image (5)](https://github.com/user-attachments/assets/78af7ce8-cf09-4905-92a4-516b0f4033ee)

**Comment by signedav** [comment]
works here 
![image](https://github.com/user-attachments/assets/ee4f2b4e-1d42-461e-8ce8-aa041e6bea3a)

does not work here 

![image](https://github.com/user-attachments/assets/5f854e6b-b665-4978-8262-1fbf5291c4b1)

**Comment by signedav** [comment]
Could anyone test this version?

[QgisModelBaker.zip](https://github.com/user-attachments/files/16279252/QgisModelBaker.zip)

- uninstall Model Baker 
- install from ZIP
  
![image](https://github.com/user-attachments/assets/eae5b7e3-fc11-4702-a928-ded1937bb3f9)

**Comment by webrian** [comment]
> Could anyone test this version?
> 
> [QgisModelBaker.zip](https://github.com/user-attachments/files/16279252/QgisModelBaker.zip)
> 
>     * uninstall Model Baker
> 
>     * install from ZIP
> 

Yes, I can confirm that this version works. I have started with a new profile as well. My versions are as follows: 

![grafik](https://github.com/user-attachments/assets/f4d696a7-8797-43ba-b6e9-c77f7ac66f76)

**Comment by romefi** [comment]
> [QgisModelBaker.zip](https://github.com/user-attachments/files/16279252/QgisModelBaker.zip)
> 
>    - uninstall Model Baker
>    -  install from ZIP

Works as well 👍

**Comment by MiKa-RegEntw** [comment]
> Could anyone test this version?
> 
> [QgisModelBaker.zip](https://github.com/user-attachments/files/16279252/QgisModelBaker.zip)
> 
> * uninstall Model Baker
> * install from ZIP
> 
> ![image](https://private-user-images.githubusercontent.com/28384354/349855368-eae5b7e3-fc11-4702-a928-ded1937bb3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQ2MzUsIm5iZiI6MTcyMTI5NDMzNSwicGF0aCI6Ii8yODM4NDM1NC8zNDk4NTUzNjgtZWFlNWI3ZTMtZmMxMS00NzAyLWE5MjgtZGVkMTkzN2JiM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDdkZjFkODkwOTQ2NGUyY2FjYTgxZDhlZmMwNTUxOWFjYjk0NTkyYzMwZDJkOGM1ZGQzMTcyZmYyOTY5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ekuzo7YULwIAayARk0CRg2TASX76QOk6p10ND1ngisc)

works also for me, thank you very much

**Comment by signedav** [comment]
Thanks for your feedback.

**Comment by KTAI-GIS** [comment]
Seems to be working
See my Log Messages below

Log Messages
Plugins
2024-07-18T12:06:00     INFO    Loaded Document Management System (package: document_management_system)
2024-07-18T12:06:01     INFO    Loaded geocat.ch Export (package: geocat_export)
2024-07-18T12:06:02     INFO    Loaded Linking Relation Editor (package: linking_relation_editor)
2024-07-18T12:06:02     INFO    Loaded NumericalDigitize (package: numericalDigitize)
2024-07-18T12:06:03     INFO    Loaded Model Baker (package: QgisModelBaker)
2024-07-18T12:06:03     INFO    Loaded DB Manager (package: db_manager)
2024-07-18T12:06:04     INFO    Loaded GRASS GIS provider (package: grassprovider)
2024-07-18T12:06:05     INFO    Loaded MetaSearch Catalog Client (package: MetaSearch)
2024-07-18T12:06:07     INFO    Loaded Processing (package: processing)
2024-07-18T12:06:09     INFO    Loaded SAGA GIS provider (package: sagaprovider)
General
2024-07-18T12:06:10     INFO    Application state:
             QGIS_PREFIX_PATH env var: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr
             Prefix: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr
             Plugin Path: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/plugins
             Package Data Path: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/.
             Active Theme Name: default
             Active Theme Path: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./resources/themes\default\icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: C:/PROGRA~1/QGIS32~1.0/apps/qgis/./svg/
              C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
              C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./svg/
             User DB Path: C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./resources/qgis.db
             Auth DB Path: C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db

2024-07-18T12:08:13     WARNING    Deprecation Warning: Trying to set a relation config directly on the relation hinweisweiteredokumenteassoc_hinweisref_dokument_T_Id. Relation settings should be done for the specific widget instance instead. Use attributeEditorRelation->setNmRelationId() or attributeEditorRelation->setForceSuppressFormPopup() instead.
2024-07-18T12:08:13     WARNING    Deprecation Warning: Trying to set a relation config directly on the relation hinweisweiteredokumenteassoc_ursprungref_dokument_T_Id. Relation settings should be done for the specific widget instance instead. Use attributeEditorRelation->setNmRelationId() or attributeEditorRelation->setForceSuppressFormPopup() instead.

Modelbaker
2024-07-18T12:06:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:06:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:06:21     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:06:23     WARNING    There was an error connecting to the database. Check connection parameters. Error details:
2024-07-18T12:06:56     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:06:56     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:06:56     WARNING    There was an error connecting to the database. Check connection parameters. Error details: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?
             connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
              Is the server running on that host and accepting TCP/IP connections?

2024-07-18T12:07:20     WARNING    There was an error connecting to the database. Check connection parameters. Error details:
2024-07-18T12:07:27     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Work/AV_Daten_AI_20240712/AI_Grenzen_V2_3_20240716c.gpkg'
2024-07-18T12:07:27     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Work/AV_Daten_AI_20240712/AI_Grenzen_V2_3_20240716c.gpkg'
2024-07-18T12:07:27     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Work/AV_Daten_AI_20240712/AI_Grenzen_V2_3_20240716c.gpkg'
2024-07-18T12:07:27     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Work/AV_Daten_AI_20240712/AI_Grenzen_V2_3_20240716c.gpkg'
2024-07-18T12:07:28     WARNING    There was an error connecting to the database. Check connection parameters. Error details: [Errno 2] No such file or directory: 'C:/Work/AV_Daten_AI_20240712/AI_Grenzen_V2_3_20240716c.gpkg'

Python warning
2024-07-18T12:07:41     WARNING    warning:C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\iliexecutable.py:83: ResourceWarning: unclosed file
              ili2db_bin = get_ili2db_bin(

             traceback: File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\execution_page.py", line 176, in _run
              if not session_widget.run():
              File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\session_panel.py", line 343, in run
              if porter.run(edited_command) != iliexecutable.IliExecutable.SUCCESS:
              File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\iliexecutable.py", line 142, in run
              ili2db_jar_arg = self._ili2db_jar_arg()
              File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\iliwrapper\iliexecutable.py", line 83, in _ili2db_jar_arg
              ili2db_bin = get_ili2db_bin(

2024-07-18T12:08:12     WARNING    warning:C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\dataobjects\project.py:138: DeprecationWarning: QgsProject.setEvaluateDefaultValues() is deprecated
              qgis_project.setEvaluateDefaultValues(self.evaluate_default_values)

             traceback: File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\workflow_wizard\project_creation_page.py", line 562, in _create_project
              project.create(None, qgis_project)
              File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libs\modelbaker\dataobjects\project.py", line 138, in create
              qgis_project.setEvaluateDefaultValues(self.evaluate_default_values)

Version
QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2<https://github.com/qgis/QGIS/commit/50adba36f2>
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009
Active Python plugins
document_management_system
0.3.3
geocat_export
v1.0.1
linking_relation_editor
v1.3.0
numericalDigitize
0.4.7
QgisModelBaker
dev
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99



Von: signedav ***@***.***>
Gesendet: Donnerstag, 18. Juli 2024 09:23
An: opengisch/QgisModelBaker ***@***.***>
Cc: Megert Pascal AI ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QgisModelBaker] There is a Problem with Version 7.9.1 (Issue #945)


Could anyone test this version?

QgisModelBaker.zip<https://github.com/user-attachments/files/16279252/QgisModelBaker.zip>

  *   uninstall Model Baker
  *   install from ZIP

image.png (view on web)<https://github.com/user-attachments/assets/eae5b7e3-fc11-4702-a928-ded1937bb3f9>

**Comment by signedav** [comment]
**7.9.3 is on its way**

Maybe you can double check when it's available in the plugin repo. Thanks, guys!
